services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: rims
      POSTGRES_USER: rims
      POSTGRES_PASSWORD: rims
    ports:
      - "5434:5432"
    volumes:
      - rims_db:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6381:6379"

volumes:
  rims_db:
